// <auto-generated />
namespace PP4.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Numero4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Numero4));
        
        string IMigrationMetadata.Id
        {
            get { return "201912082343043_Numero4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
