// <auto-generated />
namespace PP4.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _1912 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1912));
        
        string IMigrationMetadata.Id
        {
            get { return "201912180236157_19-12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
